### ISSUE TITLE
Monster slap lines 107-115: Soooo, what if someone nicked "self" needs to be slapped?

### ISSUE THREAD

**Issue by sloanonlinux** [kvirc/kvirc-scripts#22]
I haven't tried it yet but I noticed this:

`if(!$0)
    {
        echo $tr("Usage: %name - v%version")
        echo "    /slap <nick>"
        echo "    /slap self"
        echo "    /slap uninstall"
        halt;
    }
`

**Comment by un1versal** [comment]
the chances are slim but if you ever come across someone named self, run the other way.

that or edit the script

**Comment by wodim** [comment]
```
/nick uninstall
```
