### ISSUE TITLE
autoaway fails to install properly

### ISSUE THREAD

**Issue by staticfox** [kvirc/kvirc-scripts#8]
# Information
### kvirc version:

KVIrc Aria 4.3.2, revision: git-5385-g50798ae, sources date: 20150915, built on: 2015-09-18 00:51:35 UTC
### Scripts revision:

https://github.com/kvirc/kvirc-scripts/tree/33986ce6182ad95cee2ee3dc3260742aa04fc926
### Software/Hardware:

OS: Microsoft Windows 7 Ultimate  | CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz @ 4.001GHz | Mem: 14311MB/16384MB 87% used | Swap: 20279MB/32649MB used | HDD: Total: 2798GB Free: 1310.2GB Used: 53% | Net: 116.18MB in 575.36MB out on Intel(R) Ethernet Connection (2) I218-V | Display: 1440 x 900 @ 60Hz on NVIDIA GeForce GTX TITAN | Procs: 234 | UpTime: 12d 5:9:20
### Command ran:

/parse D:/stuff/kvirc-scripts-master/kvirc-scripts-master/autoaway/install.kvs
### Output:

[3:57:10 AM] Attempting to register addon "autoaway" with version 2.0.0
[3:57:10 AM] Addon successfully registered
[3:57:10 AM] Installing file 'D:\stuff\kvirc-scripts-master\kvirc-scripts-master\autoaway\pics\autoaway_128.png' into 'C:\Users\matt\AppData\Roaming\KVIrc4\pics\autoaway_128.png'
[3:57:10 AM] Installing file 'D:\stuff\kvirc-scripts-master\kvirc-scripts-master\autoaway\pics\autoaway_16.png' into 'C:\Users\matt\AppData\Roaming\KVIrc4\pics\autoaway_16.png'
[3:57:10 AM] Installing file 'D:\stuff\kvirc-scripts-master\kvirc-scripts-master\autoaway\pics\autoaway_32.png' into 'C:\Users\matt\AppData\Roaming\KVIrc4\pics\autoaway_32.png'
[3:57:10 AM] Installing file 'D:\stuff\kvirc-scripts-master\kvirc-scripts-master\autoaway\pics\autoaway_64.png' into 'C:\Users\matt\AppData\Roaming\KVIrc4\pics\autoaway_64.png'
[3:57:37 AM] [KVS] Runtime Error: Couln't find base class named 'dialog'
[3:57:37 AM] [KVS]   in script context "D:/stuff/kvirc-scripts-master/kvirc-scripts-master/autoaway/src/classes.kvs", line 5, near character 1
### Dialog appears during install:

http://i.imgur.com/wuYNjwu.png
Continued with "Yes"
*Note that running with "No" produces the same result
### Attempting to configure the addon from the manager results in this error:

[3:58:02 AM] [KVS] Runtime Error: Class 'autoaway::configure_dialog' is not defined
[3:58:02 AM] [KVS]   in script context "autoaway::configure", line 5, near character 6
[3:58:02 AM] [KVS] Runtime Error: Error in inner alias command call 'autoaway::configure', called from this context
[3:58:02 AM] [KVS]   in script context "addon::autoaway::configure", line 1, near character 1

**Comment by VFiber** [comment]
Probably related to: https://github.com/kvirc/KVIrc/issues/1601 due to missing internal KVS classes in current windows builds.

**Comment by un1versal** [comment]
Chances are this is a Application issue on Windows and theres a vague theory that maybe this could be Qt5 related + Windows,. If you can compile master with Qt4 that would help, else test Linux nightlies available and see if issue extends there, see https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc-source-or-binaries.

Also Kudos for the comprehensive bug report.

**Comment by staticfox** [comment]
Windows: I'll look in to tomorrow since compiling pretty much _anything_ on Windows is a PITA.

### Linux:

### KVirc Version

KVIrc Aria 4.3.2, revision: git-5378-g1468326, sources date: 20150915, built on: 2015-09-17 19:01:19 UTC

### Scripts Revision

https://github.com/kvirc/kvirc-scripts/tree/33986ce6182ad95cee2ee3dc3260742aa04fc926

### Software/Hardware:

matt@matt-Lenovo-Yoga-2-Pro:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

matt@matt-Lenovo-Yoga-2-Pro:~$ uname -a
Linux matt-Lenovo-Yoga-2-Pro 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The script was installed perfectly fine without error.
However, another issue arose. This may need to be opened under the main KVirc repository. All Qt menus are blank. e.g. http://i.imgur.com/YVrUpkN.jpg

Apologies for using my phone for the photo, couldn't get scrot to behave with the drop down opened.

**Comment by un1versal** [comment]
Thanks, mmm that wasnt the GTKSTYLE=ON build was it by chance?

**Comment by staticfox** [comment]
I'm not sure, this is all that is in Executable Information

KVIrc 4.3.2 'Aria'

Runtime Info:
System Name: Linux 3.19.0-26-generic
System Version: #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015
Architecture: x86_64

Build Info:
Build Date: 2015-09-17 19:01:19 UTC
Sources Date: 20150915
Revision Number: git-5378-g1468326
System Name: Linux-3.19.0-28-generic
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/x86_64-linux-gnu-g++
Compiler Flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 

I just added the PPA and apt-get upgraded (I already had KVirc installed from whatever is in the default packages list)

**Comment by un1versal** [comment]
mmm ya, that bug is probably related to Qt5+that newer Ubuntu, Some other person reported similar with KDE5 in IRC, feel free to open a report at https://github.com/kvirc/KVIrc/issues/new

If you have the possibility to compile with in LInux Qt4 and test that would also be great, and then we wait for the masters of the universe to chime in. I updated the compile instructions at https://github.com/kvirc/KVIrc/blob/master/doc/INSTALL.txt

Please uninstall that version prior to installing self compile or choose an alternative path not /usr for e.g. /usr/local or /home would be good prefix to install this to.

Thanks again this is good feedback :)

**Comment by un1versal** [comment]
You still have this issue?

**Comment by staticfox** [comment]
I do, I compiled a local build with debug enabled (finally) and it throws this error https://github.com/kvirc/KVIrc/blob/16d3c016112fac39e10c20a851bb4f229209840b/src/kvirc/kvs/object/KviKvsObjectController.cpp#L214 (not sure if already known or not)

**Comment by un1versal** [comment]
its the Qt5Xml.dll missing see https://github.com/kvirc/KVIrc/issues/1601.
If you can add that dll and test to confirm and report back to https://github.com/kvirc/KVIrc/issues/1601 we can then know how to proceed here.

**Comment by un1versal** [comment]
Still an issue?

**Comment by staticfox** [comment]
The issue still persists, yes. Same information as the initial post.

**Comment by staticfox** [comment]
Probably late, but it's resolved now.
